FROM node:22-alpine

WORKDIR /app

COPY docker-entrypoint.dev.sh /usr/local/bin/docker-entrypoint.dev.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.dev.sh

EXPOSE 8080

ENTRYPOINT ["docker-entrypoint.dev.sh"]
CMD ["npm", "run", "dev"]
