# Dockerfile.dev
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy everything else (this will be overridden by the volume mount)
COPY . .

# Expose port
EXPOSE 8080

# Run in watch mode
CMD sh -c "node ace serve --watch"